[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/nginx/access.log
    Tag               nginx.access
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/nginx/error.log
    Tag               nginx.error
    Refresh_Interval  5

[FILTER]
    Name    grep
    Match   nginx.*
    Regex   status [45][0-9][0-9]

[OUTPUT]
    Name  stdout
    Match *
    Format json_lines
